[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "fs2od"
authors = [{name = "Tomas Svoboda", email = "svoboda@ics.muni.cz"}]
dynamic = ["version", "description"]
